USE RoutineApp;

CREATE TABLE User (
	userId INT NOT NULL AUTO_INCREMENT,
    nickname VARCHAR (10) NOT NULL,
    email VARCHAR (60) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    age TINYINT UNSIGNED NOT NULL,
    gender VARCHAR(10) NOT NULL,
    profileImgUrl TEXT,
    isAdmin BOOLEAN DEFAULT FALSE,
    isPublic BOOLEAN DEFAULT TRUE,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (userId)
)
DEFAULT CHARACTER SET = utf8mb4;

CREATE TABLE Workout (
	workoutId INT NOT NULL AUTO_INCREMENT,
    userId INT,
    name VARCHAR (20) NOT NULL, 
	isTimeBased BOOLEAN DEFAULT FALSE,
    isWeightBased BOOLEAN DEFAULT TRUE,
    isCustom BOOLEAN DEFAULT TRUE,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (workoutId),
    FOREIGN KEY (userId) REFERENCES User (userId) ON DELETE CASCADE
)
DEFAULT CHARACTER SET = utf8mb4;

CREATE TABLE Tag (
	tagId INT NOT NULL AUTO_INCREMENT,
    tagName VARCHAR (15) NOT NULL UNIQUE,
    isCustom BOOLEAN DEFAULT TRUE,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (tagId)
)
DEFAULT CHARACTER SET = utf8mb4;

CREATE TABLE TagRelation (
	tagId INT NOT NULL,
    workoutId INT NOT NULL,
    PRIMARY KEY (tagId, workoutId),
    FOREIGN KEY (tagId) REFERENCES Tag (tagId) ON DELETE CASCADE,
    FOREIGN KEY (workoutId) REFERENCES Workout (workoutId) ON DELETE CASCADE
);

CREATE TABLE Routine (
	routineId INT NOT NULL UNIQUE, 
    userId INT NOT NULL,
    name VARCHAR(15) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (routineId),
    FOREIGN KEY (userId) REFERENCES User (userId) ON DELETE CASCADE
)
DEFAULT CHARACTER SET = utf8mb4;

CREATE TABLE WorkoutRelation (
	relationId INT NOT NULL UNIQUE AUTO_INCREMENT,
	routineId INT NOT NULL,
    workoutId INT NOT NULL,
    PRIMARY KEY (relationId),
    FOREIGN KEY (routineId) REFERENCES Routine (routineId) ON DELETE CASCADE,
    FOREIGN KEY (workoutId) REFERENCES Workout (workoutId) ON DELETE CASCADE
);

CREATE TABLE WorkoutSet (
	setId INT NOT NULL AUTO_INCREMENT,
    relationId INT NOT NULL,
    reps TINYINT UNSIGNED DEFAULT 1 NOT NULL,
    kgs TINYINT UNSIGNED,
    mins TINYINT UNSIGNED,
    PRIMARY KEY (setId),
    FOREIGN KEY (relationId) REFERENCES WorkoutRelation (relationId) ON DELETE CASCADE
);

CREATE TABLE Follow (
	followerId INT NOT NULL,
    followingId INT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (followerId, followingId),
    FOREIGN KEY (followerId) REFERENCES User (userId) ON DELETE CASCADE,
    FOREIGN KEY (followingId) REFERENCES User (userId) ON DELETE CASCADE
);

CREATE TABLE followPending (
	followerId INT NOT NULL,
    followingId INT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (followerId, followingId),
    FOREIGN KEY (followerId) REFERENCES User (userId) ON DELETE CASCADE,
    FOREIGN KEY (followingId) REFERENCES User (userId) ON DELETE CASCADE
);

CREATE TABLE Record (
	recordId INT NOT NULL UNIQUE AUTO_INCREMENT,
    userId INT NOT NULL,
    ymd DATETIME NOT NULL,
    isFinished BOOLEAN DEFAULT FALSE,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (recordId),
    FOREIGN KEY (userId) REFERENCES User (userId) ON DELETE CASCADE
);

CREATE TABLE RecordDetail (
	detailId INT NOT NULL UNIQUE AUTO_INCREMENT,
    recordId INT NOT NULL,
    workoutId INT NOT NULL,
    workoutName VARCHAR(20) NOT NULL,
    isFinished BOOLEAN DEFAULT FALSE NOT NULL,
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (detailId),
    FOREIGN KEY (recordId) REFERENCES Record (recordId) ON DELETE CASCADE,
    FOREIGN KEY (workoutId) REFERENCES Workout (workoutId)
)
DEFAULT CHARACTER SET = utf8mb4;

CREATE TABLE RecordSet (
	setId INT NOT NULL UNIQUE AUTO_INCREMENT,
    recordDetailId INT NOT NULL,
	reps TINYINT UNSIGNED DEFAULT 1 NOT NULL,
    mins TINYINT UNSIGNED,
    kgs TINYINT UNSIGNED
);
